In [55]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score , precision_score, recall_score, f1_score
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier

In [56]:
data = pd.read_excel(r'/home/jominstudio/Documents/Research/PhD/Course Work/Machine Learning with Python/Python/HRdata.xlsx')

In [57]:
data.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

  EducationField  Gender                JobRole  JobSatisfaction  \
0  Life Sciences  Female        Sales Executive                4   
1  Life Sciences    Male     Research Scientist                2   
2          Other    Male  Laboratory Technician                3   
3  Life Sciences  Female     Research Scientist                3   
4        Medical    Male  Laboratory Technician                2   

  MaritalStatus  ...  PercentSalaryHike PerformanceRating  \
0        Single  ...                 11                 3   
1       Married  ...                 23                 4   
2        Single  ...                 15                 3   
3       Married  ...                 11                 3   
4       Married  ...                 12                 3   

   RelationshipSatisfaction  StockOptionLevel  TotalWorkingYears  \
0                         1                 0                  8   
1                         4                 1                 10   
2                         2                 0                  7   
3                         3                 0                  8   
4                         4                 1                  6   

   TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  \
0                      0               6                   4   
1                      3              10                   7   
2                      3               0                   0   
3                      3               8                   7   
4                      3               2                   2   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     5  
1                        1                     7  
2                        0                     0  
3                        3                     0  
4                        2                     2  

[5 rows x 22 columns]

# Converting the String values to Categorical (numericals)


In [58]:
#Converting variables to numeric or string.
data['Attrition'] = data['Attrition'].astype('category')
data['BusinessTravel'].replace(['Non-Travel', 'Travel_Frequently','Travel_Rarely'],[0, 1,2], inplace=True)
data['Department'].replace(['Human Resources', 'Research & Development', 'Sales'],[0,1,2],inplace=True)
data['EducationField'].replace(['Human Resources', 'Life Sciences', 'Marketing', 'Medical', 'Other', 'Technical Degree'],[0,1,2,3,4,5],inplace=True)
data['Gender'].replace(['Female','Male'],[0,1],inplace=True)
data['JobRole'].replace(['Sales Executive', 'Research Scientist', 'Laboratory Technician', 'Manufacturing Director', 'Healthcare Representative', 'Manager', 'Sales Representative', 'Research Director', 'Human Resources'],[0,1,2,3,4,5,6,7,8], inplace=True)
data['MaritalStatus'].replace(['Divorced', 'Married', 'Single'],[0,1,2],inplace=True)
data['OverTime'].replace(['No', 'Yes'],[0,1],inplace=True)

In [59]:
data.head()

Age Attrition  BusinessTravel  Department  DistanceFromHome  \
0   41       Yes               2           2                 1   
1   49        No               1           1                 8   
2   37       Yes               2           1                 2   
3   33        No               1           1                 3   
4   27        No               2           1                 2   

   EducationField  Gender  JobRole  JobSatisfaction  MaritalStatus  ...  \
0               1       0        0                4              2  ...   
1               1       1        1                2              1  ...   
2               4       1        2                3              2  ...   
3               1       0        1                3              1  ...   
4               3       1        2                2              1  ...   

   PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  \
0                 11                  3                         1   
1                 23                  4                         4   
2                 15                  3                         2   
3                 11                  3                         3   
4                 12                  3                         4   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                 0                  8                      0               6   
1                 1                 10                      3              10   
2                 0                  7                      3               0   
3                 0                  8                      3               8   
4                 1                  6                      3               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2  

[5 rows x 22 columns]

In [60]:
corr = data.corr()
corr.style.background_gradient(cmap='coolwarm')

In [61]:
# No colinerity found with >80% correlation. Considering all the variables.

# Function of calculating Confusion Matrix with Accuracy, Precision, Recall & F1-Score Calculation

In [62]:
def fnConfusionMatrix(y_test, y_pred , algo):
    
    cm = confusion_matrix(y_test, y_pred)
    print ("ALGORITHM : " , algo)
    print ("--------------------")
    print ("Confusion Matrix : \n", cm)
    print ("Accuracy : ", accuracy_score(y_test, y_pred)*100 , "%")
    print ("Recall : ", recall_score(y_test, y_pred,average="macro")*100 , "%")
    print ("Precision : ", precision_score(y_test, y_pred,average="macro")*100 , "%")
    print ("F1-Score : ", f1_score(y_test, y_pred,average="macro")*100 , "%") 

# Function to Predict

In [63]:
def fnPredict(classifier, X_test, y_test):
    y_pred = classifier.predict(X_test)
    return y_pred


# Function to fit Logistic Regression and prediction

In [64]:
def fnLogisticRegression (X_train, X_test, y_train, y_test):
    
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X, y)
    
    y_pred = fnPredict(classifier, X_test, y_test)
    
    fnConfusionMatrix(y_test, y_pred, "Logistic Regression")
    return y_pred , classifier

# Function to fit Support Vector Machine(SVM) and Prediction

In [65]:
def fnSVM(X_train, X_test, y_train, y_test ):
    
    model = svm.SVC(kernel='poly', degree=2)
    model.fit(X_train, y_train)
    
    y_pred = fnPredict(model,X_test, y_test)
    
    fnConfusionMatrix(y_test, y_pred , "SVM")
    return y_pred , model

# Function to fit Decision Tree (Gini Method) and Prediction

In [66]:
def fnDecisionTree(X_train, X_test, y_train, y_test):
    
    # Function to perform training with giniIndex.
    #def train_using_gini(X_train, X_test, y_train):
  
    # Creating the classifier object
    clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5)
  
    # Performing training
    clf_gini.fit(X_train, y_train)
    #return clf_gini
    
    y_pred = fnPredict(clf_gini,X_test, y_test)
    
    fnConfusionMatrix(y_test, y_pred , "Decision Tree")
    return y_pred , clf_gini


# Splitting Independent and Dependent Variables 

In [67]:
# split into train test sets.
from sklearn.model_selection import train_test_split
X = data.drop('Attrition', axis=1)
y = data.Attrition

In [68]:
#print (X.columns)

# Splitting independent and dependent variables in train and test

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


# Calling Logistic Regression Classifier

In [70]:
pred_1, model1 = fnLogisticRegression(X_train, X_test, y_train, y_test )
print ("--------------------")

ALGORITHM :  Logistic Regression
--------------------
Confusion Matrix : 
 [[309   1]
 [ 57   1]]
Accuracy :  84.23913043478261 %
Recall :  50.7007786429366 %
Precision :  67.21311475409837 %
F1-Score :  47.3767258382643 %
--------------------


/home/jominstudio/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Calling Support Vector Macine (SVM) Classifier

In [71]:
pred_2 , model2 = fnSVM(X_train, X_test, y_train, y_test )
print ("--------------------")

ALGORITHM :  SVM
--------------------
Confusion Matrix : 
 [[310   0]
 [ 58   0]]
Accuracy :  84.23913043478261 %
Recall :  50.0 %
Precision :  42.119565217391305 %
F1-Score :  45.72271386430678 %
--------------------


/home/jominstudio/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Calling Decision Tree (Gini) Classifier

In [72]:
pred_3 , model3  = fnDecisionTree(X_train, X_test, y_train, y_test )
print ("--------------------")

ALGORITHM :  Decision Tree
--------------------
Confusion Matrix : 
 [[289  21]
 [ 42  16]]
Accuracy :  82.88043478260869 %
Recall :  60.40600667408231 %
Precision :  65.27721074548869 %
F1-Score :  61.92790869529517 %
--------------------


# Executing ensambling Method with voting classifier

In [73]:
voting_clf = VotingClassifier(estimators=[('SVC', model1), ('DTree', model2), ('LogReg', model3)], voting='hard')
voting_clf.fit(X_train, y_train)

preds = voting_clf.predict(X_test)

acc = accuracy_score(y_test, preds)
#l_loss = log_loss(y_test, preds)
recall_final = recall_score(y_test, preds,average="macro")*100
precision_final = precision_score(y_test, preds,average="macro")*100
f1 = f1_score(y_test, preds,average="macro")*100

print("Accuracy is: " + str(acc*100) +"%")
#print("Log Loss is: " + str(l_loss))
print("Recall Score is: " + str(recall_final)+"%")
print("Precesion Score is: " + str(precision_final)+"%")
print("F1 Score is: " + str(f1)+"%")

Accuracy is: 84.51086956521739%
Recall Score is: 51.56284760845384%
Precesion Score is: 75.662100456621%
F1 Score is: 49.05646630236794%


/home/jominstudio/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
